In [1]:
NAME = "" # put your full name here
COLLABORATORS = [] # list names of anyone you worked with on this homework.  

(A note on collaboration:  You are encouraged to learn from one another by brainstorming solution strategies. However the work you submit must clearly be your own. We will give zero credit for assignment submissions that are identical to one another. If you work with others, be sure to finish assignments on your own. Comments and markdown cells must clearly be your own.)

# [ER131] Homework 1: Introduction

Welcome to the first homework for this course! We'll go over some Python and NumPy exercises, as well as some mathematics that are helpful for this course. 

Many of the cells in this notebook contain pre-written code that you can test for yourself. Any cell that says "Exercise x" or "Question x.y" is followed by an assignment for you to complete; these are the parts of the notebook that will be graded.

## Table of Contents
1 - [Python](#python)<br>
2 - [NumPy](#NumPy)<br>
3 - [Optional: Linear Algebra](#LinAlg)<br>

**Dependencies:**

In [2]:
# Run this cell to import the packages you will need to complete this homework
import math
import numpy as np
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import pandas as pd

----

## Section 1: Python  <a id='python'></a>

Python is the main programming language we'll use in the course. Work through the following cells and make sure you understand what is happening in each.

Feel free to review one or more of the following materials as a refresher.

- **[Python Tutorial](https://docs.python.org/3.5/tutorial/)**: Introduction to Python from the creators of Python
- **[Composing Programs Chapter 1](https://www.composingprograms.com/pages/11-getting-started.html)**: This is more of a introduction to programming with Python.
- **[Advanced Crash Course](http://cs231n.github.io/python-numpy-tutorial/)**: A fast crash course which assumes some programming background.
- **[Jupyter Notebook Basics](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Notebook%20Basics.html)**: A guide to navigating Jupyter Notebooks, including different parts of the user interface and different ways that cells can be used.

<br>

### Mathematical Expressions

In this section, we'll go over some basic mathematical expressions in Python.

In [3]:
# In Python, the ** operator performs exponentiation.
math.sqrt(math.e ** (-math.pi + 8))

11.349840298425361

**Question 1.1:** Multiply eleven by seven raised to the power of three plus one. Then, add eight and then divide by 100.

In [4]:
#YOUR CODE HERE

#Solution
# (11*(7**3+1)+8)/100 # one solution
(11*(math.pow(7,3)+1)+8)/100 #another solution

37.92

### Output and Printing

**Question 1.2:** One at a time, uncomment and run each of the three lines of code below. Without modifying the text itself, change the second line of code so that it prints without errors. 

In [5]:
print('Hello' + ',', 'world!')
#'Why didn't this line print?'
#"Hello, cell" + " output!"

Hello, world!


*Solution: The second line of code didn't print because Python interprets the apostrophe in the word "didn't" as the end quote of the string. To fix the error and print the second line, you could use use double quotation marks to denote the beginning and end of the string, i.e.,*

`"Why didn't this line print?"`

### For Loops

**Question 1.3:** Run the loop below. Then, comment out the "else" statement (lines 6 and 7). Describe what happens when you remove this statement and explain why it happens. 

In [6]:
# A for loop repeats a block of code once for each element in a given collection.
for i in range(10):
    if i % 3 == 0:
        print(3**i)
    else:
        print("Odd power of 3")  # What happens if you remove the "else" statement?

1
Odd power of 3
Odd power of 3
27
Odd power of 3
Odd power of 3
729
Odd power of 3
Odd power of 3
19683


*YOUR ANSWER HERE*

*Solution: When we remove the "else" statement, the function "passes" for every power of three integer; i.e., the for loop continues to the next even number in the range without printing anything.*

### Strings ([Reference](https://developers.google.com/edu/python/strings))

Run the code in the two cell blocks below. Notice the errors that occur when you uncomment line 5 in the first block and line 2 in the second block.

In [7]:
s = 'hi'
print(s[1])         ## i
print(len(s))       ## 2
print(s + ' there')
#s[1] = 'a' # why doesn't this work?

i
2
hi there


In [8]:
avos_num = 6.022 * 10**23
#text = "The value of Avogadro's number is " + avos_num      ## NO, does not work
text = "The value of Avogadro's number is "  + str(avos_num)  ## yes
print(text)

The value of Avogadro's number is 6.0219999999999996e+23


**Question 1.4:** Write a line of code that will print the statement "The limit of the universe is 3.142e+00" without explicitly typing out the number. (Note: in this case, it's okay if your code prints more than three decimal places.)

In [9]:
# YOUR CODE HERE
# possible solution
print('The limit of the universe is ' + str(np.format_float_scientific(np.pi, 3)))

The limit of the universe is 3.142e+00


### Lists ([Reference](https://docs.python.org/3.5/tutorial/introduction.html#lists))

In [10]:
squares = [2, 4, 9, 16, 25, 36]
squares

[2, 4, 9, 16, 25, 36]

Practice subsetting lists by running the code in the cell block below.

In [11]:
print(squares[0])
print(squares[-1])
print(squares[-3:])
print(squares[:])
print(squares + [49, 64, 81, 100])

2
36
[16, 25, 36]
[2, 4, 9, 16, 25, 36]
[2, 4, 9, 16, 25, 36, 49, 64, 81, 100]


**Question 1.5:** Insert 444 as the third element in `squares` such that `squares` = [2, 4, 9, 444, 16, 25, 36].

In [12]:
# YOUR CODE HERE

# SOLUTION
# squares[3] = 444 # doesn't work because it replaces the fifth element (13) with 11. 
# print(squares)
squares = squares[0:3] + [444] + squares[3:] # one solution
squares
# squares.insert(3,444) # another solution
# squares

[2, 4, 9, 444, 16, 25, 36]

**Question 1.6:** Since 2 and 444 are not actually a square of anything, remove both numbers in `squares` such that `squares` = [4, 9, 16, 25, 36].

In [13]:
# YOUR CODE HERE

# possible solution


# REDO THE SOLUTION
squares = squares[1:]

### Dictionaries ([Reference](https://realpython.com/python-dicts/))

Practice building and modifying dictionaries by running the lines of code below.

In [14]:
tel = {'duncan': 343, 'colette': 739, 'natalie': 841, 'kaz': 333}
tel['salma'] = 369
del tel['kaz']

In [15]:
tel

{'duncan': 343, 'colette': 739, 'natalie': 841, 'salma': 369}

**Question 1.6:** Write a line of code that returns the three-digit extension (i.e., the value) associated with the key 'natalie.'

In [16]:
# YOUR CODE HERE

# SOLUTION
tel['natalie']

841

### Defining Functions

Here's an example of a function:

In [17]:
def add2(x):
    """This docstring explains what this function does: it adds 2 to a number."""
    return x + 2

#### Getting Help

In [18]:
help(add2)

Help on function add2 in module __main__:

add2(x)
    This docstring explains what this function does: it adds 2 to a number.



**Question 1.7:** Fill in the ellipses in the function `print_extension`, which takes in a dictionary `phonebook` and string `name` and returns a string stating the three-digit value associated with the key `name`. For example:

    >>> print_extension(tel, 'richard')
    'The extension for richard is 3698.'

In [19]:
# REPLACE THE ELLIPSES WITH YOUR CODE

def print_extension(phonebook,name):
    value = ... # From the dictionary `phonebook,` extract the value associated with key `name`
    return ... # Print the string "The extension for [name] is [value].", where [name] and [value] correspond to the appropriate key-value pair from the dictionary `phonebook.  
    ### END SOLUTION

# TEST YOUR CODE
print_extension(tel,'salma')

Ellipsis

In [20]:
### EXAMPLE SOLUTION

def print_extension(phonebook,name):
    value = phonebook[name] # From the dictionary `phonebook,` extract the value associated with key `name`
    return print('The extension for ' + name + ' is ' + str(value) + '.') # Print the string "The extension for [name] is [value].", where [name] and [value] correspond to the appropriate key-value pair from the dictionary `phonebook.
#     return print('The extension for {} is {}.'.format(name, value)) # An alternative solution
    ### END SOLUTION
    
print_extension(tel,'salma')    

The extension for salma is 369.


**Question 1.8:** Write a function `case_check` that takes in a list of strings and returns `True` only if the *last letter* of all items in the list is lower case. 


    >>> case_check(['duncan','julia','akshay','christian','richard'])
    True
    >>> case_check(['Instructor','GSI','Reader','CA','CA'])
    False

Hint: the built-in [`.islower()`](https://www.geeksforgeeks.org/isupper-islower-lower-upper-python-applications/) method might be useful. 

In [23]:
def case_check(strings):
    ### YOUR CODE HERE
    
    raise NotImplementedError()

In [24]:
def case_check(strings):
    ### BEGIN SOLUTION
    flag = True # variable that one string with a upper-case last letter is found
    for i in strings:
        if i[-1].islower():
            pass # if it is, continue to the next item in the list. 
        else:
            flag = False # if it isn't, set the flag to False
    
    return flag
    ### END SOLUTION

In [25]:
assert case_check(['duncan','colette','natalie','kaz','salma']) == True 
assert case_check(['Instructor','GSI','READER','CA','CA']) == False
assert case_check(['NY','CA','NJ','CO','AK']) == False 
assert case_check(['a capella','Llamas','ambidextrous','Kansas']) == True 

**Question 1.9:** Write a function `squares_dict` that takes in a list of numbers `l` and creates a dictionary that records the the square of each number and multiplies it by 10.

    >>> print(squares_dict([0,1,2,4]))
    {0: 0, 1: 10, 2: 40, 4: 160}
    
It might be helpful to [review dictionaries in Python](https://docs.python.org/3/tutorial/datastructures.html#dictionaries).

In [26]:
# REPLACE THE ELLIPSES WITH YOUR CODE

def squares_dict(l):
    squares = {} # initialize dictionary to hold the squared numbers

    for number in ...:
        ...

    return squares
    ### END SOLUTION

In [27]:
def squares_dict(l):
    ### BEGIN SOLUTION
    squares = {} # initialize dictionary to hold the squared numbers

    for number in l:
        squares[number] = (number**2)*10

    return squares
    ### END SOLUTION

In [28]:
assert squares_dict([0,1,2,4])=={0: 0, 1: 10, 2: 40, 4: 160}
assert squares_dict([3])=={3: 90}

---

## Section 2: NumPy <a id='NumPy'></a>

The `NumPy` library lets us do fast, simple computing with numbers in Python. 

If the following section is a little difficult, we've provided some resources for review:

* [DS100 Numpy Review](http://ds100.org/fa17/assets/notebooks/numpy/Numpy_Review.html)
* [Condensed Numpy Review](http://cs231n.github.io/python-numpy-tutorial/#numpy)
* [The Official Numpy Tutorial](https://numpy.org/doc/stable/user/quickstart.html)

<br>

**Jupyter pro-tip**: Pull up the docs for any function in Jupyter by running a cell with
the function name and a `?` at the end:

In [29]:
np.arange?

**Another Jupyter pro-tip**: Pull up the docs for any function in Jupyter by typing the function
name, then `<Shift>-<Tab>` on your keyboard. Super convenient when you forget the order
of the arguments to a function. You can press `<Tab>` multiple tabs to expand the docs. Pressing `<Tab>` does an autocomplete, but doesn’t pull up docs.


Try it on the function below:

In [30]:
np.linspace # what parameters will this function accept? What type do they need to be?

<function numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)>

In this section, we will use numpy to answer some questions about the California Independent System Operator (CAISO) Daily Renewables Watch. This data records the hourly production of various renewable resources as well as a hourly breakdown of total production of resource type, both in megawatts (MW). For an idea of how the dataset is formatted, click [here](http://content.caiso.com/green/renewrpt/20180617_DailyRenewablesWatch.txt). 

**Question 2.1:** Use numpy operations to output an array containing the hourly values of solar photovoltaic and solar thermal production. You should create a single array with two columns and each row corresponding to an hour of generation. Examine the result. What odd pattern appeared in solar production that day? Can you explain it?

In [31]:
# The following line loads the data for this question.  
# Note that it uses Pandas -- we'll learn more about that next week!  
# But the output is a numpy array.  
data1 = pd.read_csv("data/q2_1.csv").values 

# YOUR CODE HERE

*COMMENT ON THE RESULT HERE*

In [32]:
#BEGIN SOLUTION
# from the CAISO link and from opening the csv, we know that the last 2 columns are 
# solar PV and solar thermal - so we can output just those 2 columns
data1[:,[-2,-1]] # this is one way of writing this code - selecting the last 2 columns
data1[:,[7,8]] # we can also specify that we want columns 7 and 8

#END SOLUTION----

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [174, 0],
       [2376, 0],
       [5484, 86],
       [5312, 141],
       [3503, 110],
       [6329, 201],
       [8700, 472],
       [8857, 527],
       [8732, 598],
       [7983, 395],
       [7020, 262],
       [5329, 228],
       [2193, 119],
       [114, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=object)

*Answer: The odd pattern that appears is that there's a dip in solar production from about 10 am - 1 pm. This is because this data is from the August 2017 solar eclipse. Normally, we would expect increasing solar production until the mid-afternoon peak.*

**Question 2.2:** Use numpy operations to answer the following question: How much more wind than geothermal electricity was generated in April 2017? Note, each entry in the array represents energy produced for a given *hour*.

In [33]:
data2 = pd.read_csv("data/q2_2.csv").values

# YOUR CODE HERE

In [34]:
# ### BEGIN SOLUTION
wind_apr = np.sum(data2[:,6])
geot_apr = np.sum(data2[:,2])
wind_apr - geot_apr 
# ### END SOLUTION

723677

**Question 2.3:** What percentage of the total resource count did biomass and biogas together represent on July 4th, 2017 (Independence Day) in California?

In [35]:
data3 = pd.read_csv("data/q2_3.csv").values

# YOUR CODE HERE

In [36]:
# ### BEGIN SOLUTION
(np.sum(data3[:,3]) + np.sum(data3[:,4])) / np.sum(data3[:,2:]) * 100
# ### END SOLUTION

5.2917858397310455

## Optional: Using NumPy for Linear Algebra <a id='LinAlg'></a>

We'll continue the math review with a short (optional) section on using numpy arrays and matrix multiplication.

### NumPy Arrays

In [37]:
# A numpy array can be multi-dimensional
multi_dim = np.array([
    [2, 2, 2,],
    [3, 3, 3],
    [30, 20, 10]
])

print(multi_dim)

[[ 2  2  2]
 [ 3  3  3]
 [30 20 10]]


Using multi-dimensional arrays in numpy allows us to use all of the numpy functions, which we cannot apply to multi-dimensional lists. Below are a few examples of numpy arrays that might be useful in future assignments. 

In [38]:
print(multi_dim.argmax())
print(multi_dim.argmin())

copy = multi_dim.copy()
print(copy)

6
0
[[ 2  2  2]
 [ 3  3  3]
 [30 20 10]]


**Question 3.1:** Explain what each function above is printing. 

YOUR ANSWER HERE

**Question 3.2:** What is one additional function that is useful in NumPy? And what does it do?

_**Hint:** To find all functions, create a multi-dimensional matrix (name it 'my_multi_dim'), write a "." after the name, and then hit 'Shift' + 'Tab' to see a list of available functions. Otherwise, you can view the NumPy documentation to browse the functionality._ 

YOUR ANSWER HERE

Indexing in multi-dimensional arrays requires indicating the place of each dimension of interest.

In [39]:
print(multi_dim[0])
print(multi_dim[0,0])
print(multi_dim[2,0])

[2 2 2]
2
30


**Question 3.3:** Return the array [30, 20] by indexing from the `multi_dim` array. 

In [40]:
# YOUR CODE HERE

In [41]:
# SOLUTION
multi_dim[2,:2]

array([30, 20])

We can also manipulate arrays in some interesting ways. For example, we can change all values in an array by using basic PEMDAS (parenthases, exponents, multiplication, division, addition, subtraction) operations. 

In [42]:
double_array = multi_dim*2
print(double_array)

add_array = multi_dim + 2
print(add_array)

[[ 4  4  4]
 [ 6  6  6]
 [60 40 20]]
[[ 4  4  4]
 [ 5  5  5]
 [32 22 12]]


**Question 3.4:** Divide every value in the `multi_dim` array by 2 and add 10 to the first three elements in the array such that `div_array` = [11, 11, 11].

In [43]:
# YOUR CODE HERE
div_array = ...

In [44]:
# SOLUTION
x = multi_dim / 2
div_array = x[0] + 10
print(div_array)

[11. 11. 11.]


### Linear Algebra

In this question, we'll ask you to use your linear algebra knowledge to fill in NumPy matrices. To conduct matrix multiplication in NumPy, you should write code like the following:

In [45]:
# A matrix in NumPy is simply a 2-dimensional NumPy array
matA = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

matB = np.array([
    [10, 11],
    [12, 13],
    [14, 15],
])

# The notation B @ v means: compute the matrix multiplication Bv
matA @ matB

array([[ 76,  82],
       [184, 199]])

You can also use the same syntax to do matrix-vector multiplication or vector dot products. Handy!

In [46]:
matA = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

# A vector in NumPy is simply a 1-dimensional NumPy array
some_vec = np.array([ 10, 12, 14, ])

another_vec = np.array([ 10, 20, 30 ])

print(matA @ some_vec)
print(some_vec @ another_vec)

[ 76 184]
760


Sofia, Pete, and Rowan are shopping for fruit at Berkeley Bowl. Berkeley Bowl, true to its name, only sells fruit bowls. A fruit bowl contains some fruit and the price of a fruit bowl is the total price of all of its individual fruit.

Berkeley Bowl has bananas for \\$2.00, plums for \\$3.00, and dragon fruit for \\$7.00 (expensive!). These prices can be written in a vector:

$$
\vec{v} = \begin{bmatrix}
     2 \\
     3 \\
     7 \\
\end{bmatrix}
$$

Berkeley Bowl sells the following fruit bowls:

1. 2 of each fruit
2. 6 bananas and 2 plums
3. 5 dragon fruit


**Question 3.4:** Create a 2-dimensional numpy array encoding the matrix $B$ such that the matrix-vector multiplication

$$
B\vec{v}
$$

evaluates to a length 3 column vector containing the price of each fruit bowl. The first entry of the result should be the cost of fruit bowl #1, the second entry the cost of fruit bowl #2, etc.

In [47]:
import numpy as np
v = np.array([2,3,7])

# Fill in B
# B = ... # REPLACE ELIPSES WITH YOUR CODE

### BEGIN OPTIONAL SOLUTION
B = np.array([
    [2, 2, 2], # bowl 1
    [6, 2, 0], # bowl 2
    [0, 0, 5], # bowl 3
])
### END SOLUTION

# The notation B @ v means: compute the matrix multiplication Bv
B @ v

array([24, 18, 35])

----

## Submission

Congrats, you're done with homework 1!

Before you submit, click **Kernel** --> **Restart & Clear Output**. Then, click **Cell** --> **Run All**. Then, go to the toolbar and click **File** -> **Download as** -> **.html** and submit the file through bCourses.

----

### Bibliography

+ Data 100 - HW 1: Introduction